DROP EXTENSION IF EXISTS pgcrypto;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM mqtt;
REVOKE CREATE, USAGE ON SCHEMA public FROM mqtt;
REVOKE CONNECT, TEMPORARY ON DATABASE mqtt FROM mqtt;
